go:
    # Whenever the Go version is updated here,
    # .circle/config.yml should also be updated.
    version: 1.20
repository:
    path: github.com/aashley/powerpal_exporter
build:
    flags: -a -tags netgo
    ldflags: |
        -X github.com/prometheus/common/version.Version={{.Version}}
        -X github.com/prometheus/common/version.Revision={{.Revision}}
        -X github.com/prometheus/common/version.Branch={{.Branch}}
        -X github.com/prometheus/common/version.BuildUser={{user}}@{{host}}
        -X github.com/prometheus/common/version.BuildDate={{date "20060102-15:04:05"}}
tarball:
    files:
        - LICENSE
crossbuild:
    platforms:
        - linux/amd64
        - linux/arm
        - linux/arm64
        - linux/ppc64le
        - windows/amd64