---
version: 2.1

orbs:
  prometheus: prometheus/prometheus@0.16.0

executors:
  # Whenever the Go version is updated here, .promu.yml
  # should also be updated.
  golang:
    docker:
    - image: cimg/golang:1.18.1
    parameters:
      working_dir:
        type: string
        default: ~/project
    working_directory: << parameters.working_dir >>

jobs:
  test:
    executor: golang

    steps:
    - prometheus/setup_environment
    - run: sudo apt-get -y install build-essential libsnmp-dev
    - run: make
    - run: git diff --exit-code
    - prometheus/store_artifact:
        file: powerpal_exporter

workflows:
  version: 2
  snmp_exporter:
    jobs:
#    - test:
#        filters:
#          tags:
#            only: /.*/
    - prometheus/build:
        name: build
        filters:
          tags:
            only: /.*/
    - prometheus/publish_main:
        requires:
        - build
        filters:
          branches:
            only: main
        docker_hub_organization: adamashley
        context:
          - Docker
    - prometheus/publish_release:
        requires:
        - build
        filters:
          tags:
            only: /^v[0-9]+(\.[0-9]+){2}(-.+|[^-.]*)$/
          branches:
            ignore: /.*/
        docker_hub_organization: adamashley
        context:
          - Docker